---
name: Test

on:
  pull_request: {}
  push:
    branches:
      - master
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Run rake rubocop
        run: bundle exec rake rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.2"
          - ruby: "3.1"
          - ruby: "3.0"
          - ruby: "2.7"
    env:
      COVERAGE: ${{ matrix.coverage }}
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
      - name: Verify gem builds
        run: gem build --strict --verbose *.gemspec
  tests:
    needs:
      - rubocop
      - test
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
